// Build a show for a song, without opening the app.
//
//   node tools/make-show.js <file.wav> ["Show name"] [--style calm|balanced|energetic]
//
// Takes a 16-bit PCM WAV (what `decodeAudioData` gives you, and what the engine's media
// cache holds), analyses it with the same code the Song page runs, patches the house rig
// and runs the same generator the "Generate show" button runs. The result is an ordinary
// show file: open it in Edit mode and change anything.
//
// WAV only. The browser decodes mp3, m4a and the rest; Node has no decoder, so convert
// first — or just load the song in the app, which caches a copy the engine can read.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { basename, join } from 'node:path';

import { analyzeAudio } from '../shared/analysis/analyze.js';
import { generateShow } from '../shared/autogen.js';
import { createShow, exportShow, normalizeShow } from '../shared/show.js';
import { validateShow } from '../shared/validate.js';
import { buildFixtures, describeRig } from './rig.js';
import { projectRoot } from './demo-song.js';

/** Decode a 16-bit PCM WAV into float channels. Chunk-walking, so odd extra chunks are fine. */
export function decodeWav(buf) {
  if (buf.length < 44 || buf.toString('latin1', 0, 4) !== 'RIFF' || buf.toString('latin1', 8, 12) !== 'WAVE') {
    throw new Error('Not a WAV file. Convert the song to WAV first, or load it in the app once so the engine caches a copy.');
  }
  let fmt = null;
  let data = null;
  let at = 12;
  while (at + 8 <= buf.length) {
    const id = buf.toString('latin1', at, at + 4);
    const size = buf.readUInt32LE(at + 4);
    const body = at + 8;
    if (id === 'fmt ') fmt = { format: buf.readUInt16LE(body), channels: buf.readUInt16LE(body + 2), rate: buf.readUInt32LE(body + 4), bits: buf.readUInt16LE(body + 14) };
    else if (id === 'data') data = buf.subarray(body, Math.min(body + size, buf.length));
    at = body + size + (size % 2); // chunks are word aligned
  }
  if (!fmt || !data) throw new Error('That WAV has no fmt or data chunk.');
  if (fmt.format !== 1 || fmt.bits !== 16) throw new Error(`Only 16-bit PCM WAV is supported (this is ${fmt.bits}-bit, format ${fmt.format}).`);
  const frames = Math.floor(data.length / (2 * fmt.channels));
  const channels = Array.from({ length: fmt.channels }, () => new Float32Array(frames));
  for (let i = 0; i < frames; i++) {
    for (let c = 0; c < fmt.channels; c++) channels[c][i] = data.readInt16LE((i * fmt.channels + c) * 2) / 32768;
  }
  return { channels, sampleRate: fmt.rate };
}

export function buildShowFor(wav, { name, style = 'balanced', fileName }) {
  const audio = decodeWav(wav);
  const result = analyzeAudio(audio);
  const { beats, downbeat, beatsPerBar, ...analysis } = result;

  const show = createShow(name);
  show.meta.notes = `Generated by tools/make-show.js from ${fileName}. ${describeRig()}`;
  show.audio = {
    name: fileName,
    hash: createHash('sha256').update(wav).digest('hex'),
    durationMs: Math.round(result.durationMs),
    sampleRate: audio.sampleRate,
  };
  show.fixtures = buildFixtures();
  show.tempo = { bpm: result.bpm, beats, downbeat, beatsPerBar, offset: beats[0] ?? 0 };
  show.analysis = analysis;
  show.timeline.durationMs = Math.round(result.durationMs);
  show.timeline = generateShow(show, { style });

  const normalized = normalizeShow(show);
  const validation = validateShow(normalized);
  return { show: exportShow(normalized, validation), analysis: result, validation };
}

function main() {
  const args = process.argv.slice(2);
  let style = 'balanced';
  const rest = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--style') style = args[++i] ?? style;
    else rest.push(args[i]);
  }
  const file = rest[0];
  if (!file) {
    console.error('Usage: node tools/make-show.js <file.wav> ["Show name"] [--style calm|balanced|energetic]');
    process.exit(1);
  }
  const name = rest[1] || basename(file).replace(/\.[^.]+$/, '');
  // The engine's media cache names files by their hash, so a path from there would put a
  // 64-character hash where the song's name belongs in the app. Fall back to the show name.
  const base = basename(file);
  const fileName = /^[0-9a-f]{64}$/.test(base) ? `${name}.wav` : base;

  process.stdout.write(`Reading ${fileName}… `);
  const wav = readFileSync(file);
  console.log(`${(wav.length / 1048576).toFixed(1)} MB`);

  process.stdout.write('Analysing… ');
  const { show, analysis, validation } = buildShowFor(wav, { name, style, fileName });
  console.log(`${analysis.bpm} BPM (confidence ${analysis.confidence.toFixed(2)}), ${analysis.sections.length} sections, ${analysis.drops.length} drops`);
  for (const s of analysis.sections) {
    const fmt = (ms) => `${Math.floor(ms / 60000)}:${String(Math.floor((ms % 60000) / 1000)).padStart(2, '0')}`;
    console.log(`    ${fmt(s.start)} – ${fmt(s.end)}  ${s.label.padEnd(10)} energy ${s.energy.toFixed(2)}`);
  }
  for (const i of validation.issues) console.log(`  ${i.level === 'error' ? 'ERROR  ' : 'warning'} ${i.message}`);

  const dir = join(projectRoot(), 'shows');
  mkdirSync(dir, { recursive: true });
  const out = join(dir, `${name}.dmxshow.json`);
  writeFileSync(out, `${JSON.stringify(show, null, 2)}\n`);
  console.log(`\nWrote ${out}\n  ${show.fixtures.length} fixtures, ${show.timeline.clips.length} clips, ${validation.errors} errors, ${validation.warnings} warnings`);
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) main();
